# Generated by Django 6.0.4 on 2026-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian')], default='North Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='customizable',
            field=models.BooleanField(default=True),
        ),
    ]
