# Generated by Django 6.0.4 on 2026-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_menuitem_cuisine_menuitem_customizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cuisine',
            field=models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Beverages', 'Beverages')], default='North Indian', max_length=50),
        ),
    ]
